global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hf_inference_api'
    static_configs:
      - targets: ['hf_service:80'] # Since its in the same network, we can just use the container name and internal port
    metrics_path: /api/metrics     # Path Nginx exposes for metrics